# TYPE   DATABASE        USER         ADDRESS      METHOD
local    all             postgres                  peer
local    all             all                       peer
hostssl  replication     replicator   all          scram-sha-256
hostssl  postgres        rewinder     all          scram-sha-256
hostssl  all             postgres     all          scram-sha-256 clientcert=verify-ca
hostssl  all             all          all          scram-sha-256
hostnossl all            all          all          reject
