use std::{
    env,
    error::Error,
    ffi::OsStr,
    fmt, fs,
    path::{Path, PathBuf},
};

use proc_macro2::LineColumn;
use syn::{
    spanned::Spanned,
    visit::{self, Visit},
    Attribute, Fields, ItemEnum, ItemStruct,
};
use walkdir::WalkDir;

type AppResult<T> = Result<T, Box<dyn Error>>;

fn main() {
    match run() {
        Ok(()) => {}
        Err(error) => {
            eprintln!("{error}");
            std::process::exit(1);
        }
    }
}

fn run() -> AppResult<()> {
    let repo_root = env::current_dir()?;
    let output_path = resolve_output_path(&repo_root)?;
    let rust_files = collect_rust_files(&repo_root, ["src", "tests"])?;
    let extracted_items = rust_files.into_iter().try_fold(
        Vec::new(),
        |items, relative_path| -> AppResult<Vec<ExtractedType>> {
            let source_path = repo_root.join(&relative_path);
            let source = fs::read_to_string(&source_path)?;
            let line_starts = compute_line_starts(&source);
            let parsed_file =
                syn::parse_file(&source).map_err(|error| InventoryError::ParseFailed {
                    path: relative_path.clone(),
                    source: error,
                })?;
            let collector = TypeCollector::new(relative_path.clone(), &source, &line_starts);
            let collected = collector.collect(&parsed_file)?;
            Ok(items.into_iter().chain(collected).collect())
        },
    )?;

    let rendered = render_inventory(&extracted_items);
    fs::write(&output_path, rendered)?;

    println!(
        "wrote {} type declarations to {}",
        extracted_items.len(),
        output_path.display()
    );

    Ok(())
}

fn resolve_output_path(repo_root: &Path) -> AppResult<PathBuf> {
    match env::args_os().nth(1) {
        Some(path) => {
            let candidate = PathBuf::from(path);
            if candidate.is_absolute() {
                Ok(candidate)
            } else {
                Ok(repo_root.join(candidate))
            }
        }
        None => Ok(repo_root.join("type_inventory.txt")),
    }
}

fn collect_rust_files(
    repo_root: &Path,
    roots: impl IntoIterator<Item = &'static str>,
) -> AppResult<Vec<PathBuf>> {
    let files =
        roots
            .into_iter()
            .try_fold(Vec::new(), |files, root| -> AppResult<Vec<PathBuf>> {
                let root_path = repo_root.join(root);
                if !root_path.exists() {
                    return Ok(files);
                }

                let discovered = WalkDir::new(root_path)
                    .into_iter()
                    .collect::<Result<Vec<_>, _>>()?
                    .into_iter()
                    .filter(|entry| entry.file_type().is_file())
                    .filter(|entry| entry.path().extension() == Some(OsStr::new("rs")))
                    .map(|entry| {
                        entry
                            .path()
                            .strip_prefix(repo_root)
                            .map(Path::to_path_buf)
                            .map_err(|error| -> Box<dyn Error> { Box::new(error) })
                    })
                    .collect::<Result<Vec<_>, _>>()?;

                Ok(files.into_iter().chain(discovered).collect())
            })?;

    let mut sorted_files = files;
    sorted_files.sort();
    Ok(sorted_files)
}

fn compute_line_starts(source: &str) -> Vec<usize> {
    let starts = source
        .char_indices()
        .filter_map(|(idx, ch)| if ch == '\n' { Some(idx + 1) } else { None })
        .fold(vec![0usize], |starts, next_start| {
            starts.into_iter().chain([next_start]).collect()
        });

    starts
}

fn render_inventory(extracted_items: &[ExtractedType]) -> String {
    let mut rendered = String::from(
        "// Generated by `cargo run --manifest-path tools/type_inventory_gen/Cargo.toml -- type_inventory.txt`\n\
         // Exhaustive snapshot of every struct and enum declaration under `src/` and `tests/`.\n\n",
    );

    extracted_items.iter().for_each(|item| {
        rendered.push_str("// path: '");
        rendered.push_str(&item.path.to_string_lossy());
        rendered.push_str("'\n");
        rendered.push_str("// line: ");
        rendered.push_str(&item.line.to_string());
        rendered.push('\n');
        rendered.push_str(item.snippet.trim_end());
        rendered.push_str("\n\n");
    });

    rendered
}

#[derive(Clone)]
struct ExtractedType {
    path: PathBuf,
    line: usize,
    snippet: String,
}

struct TypeCollector<'a> {
    path: PathBuf,
    source: &'a str,
    line_starts: &'a [usize],
    items: Vec<ExtractedType>,
    errors: Vec<InventoryError>,
}

impl<'a> TypeCollector<'a> {
    fn new(path: PathBuf, source: &'a str, line_starts: &'a [usize]) -> Self {
        Self {
            path,
            source,
            line_starts,
            items: Vec::new(),
            errors: Vec::new(),
        }
    }

    fn collect(mut self, parsed_file: &syn::File) -> AppResult<Vec<ExtractedType>> {
        self.visit_file(parsed_file);
        match self.errors.into_iter().next() {
            Some(error) => Err(Box::new(error)),
            None => Ok(self.items),
        }
    }

    fn push_struct(&mut self, item: &ItemStruct) {
        let start = item
            .attrs
            .first()
            .map(Attribute::span)
            .unwrap_or(item.struct_token.span)
            .start();
        let end = item_struct_end(item);
        self.push_item(start, end);
    }

    fn push_enum(&mut self, item: &ItemEnum) {
        let start = item
            .attrs
            .first()
            .map(Attribute::span)
            .unwrap_or(item.enum_token.span)
            .start();
        let end = item.brace_token.span.close().end();
        self.push_item(start, end);
    }

    fn push_item(&mut self, start: LineColumn, end: LineColumn) {
        let start_offset = line_column_to_offset(self.line_starts, self.source.len(), start);
        let end_offset = line_column_to_offset(self.line_starts, self.source.len(), end);
        match (start_offset, end_offset) {
            (Some(snippet_start), Some(snippet_end)) => {
                match self.source.get(snippet_start..snippet_end) {
                    Some(snippet) => self.items.push(ExtractedType {
                        path: self.path.clone(),
                        line: start.line,
                        snippet: snippet.to_string(),
                    }),
                    None => self.errors.push(InventoryError::InvalidSpan {
                        path: self.path.clone(),
                        line: start.line,
                        column: start.column,
                    }),
                }
            }
            _ => self.errors.push(InventoryError::InvalidSpan {
                path: self.path.clone(),
                line: start.line,
                column: start.column,
            }),
        }
    }
}

impl<'ast> Visit<'ast> for TypeCollector<'_> {
    fn visit_item_struct(&mut self, item: &'ast ItemStruct) {
        self.push_struct(item);
        visit::visit_item_struct(self, item);
    }

    fn visit_item_enum(&mut self, item: &'ast ItemEnum) {
        self.push_enum(item);
        visit::visit_item_enum(self, item);
    }
}

fn item_struct_end(item: &ItemStruct) -> LineColumn {
    match &item.fields {
        Fields::Named(named) => named.brace_token.span.close().end(),
        Fields::Unnamed(unnamed) => item
            .semi_token
            .map(|semi| semi.span.end())
            .unwrap_or_else(|| unnamed.paren_token.span.close().end()),
        Fields::Unit => item
            .semi_token
            .map(|semi| semi.span.end())
            .unwrap_or_else(|| item.ident.span().end()),
    }
}

fn line_column_to_offset(
    line_starts: &[usize],
    source_len: usize,
    line_column: LineColumn,
) -> Option<usize> {
    let line_start = line_column
        .line
        .checked_sub(1)
        .and_then(|index| line_starts.get(index).copied())?;
    let next_line_start = line_starts
        .get(line_column.line)
        .copied()
        .unwrap_or(source_len);
    let offset = line_start.checked_add(line_column.column)?;
    (offset <= next_line_start).then_some(offset)
}

#[derive(Debug)]
enum InventoryError {
    ParseFailed {
        path: PathBuf,
        source: syn::Error,
    },
    InvalidSpan {
        path: PathBuf,
        line: usize,
        column: usize,
    },
}

impl fmt::Display for InventoryError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ParseFailed { path, source } => {
                write!(f, "failed to parse {}: {}", path.display(), source)
            }
            Self::InvalidSpan { path, line, column } => write!(
                f,
                "failed to slice source span in {} at {}:{}",
                path.display(),
                line,
                column + 1
            ),
        }
    }
}

impl Error for InventoryError {}
