#!/usr/bin/env bash
set -euo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

readonly SOURCE_REF="${FILTERED_PR_SOURCE_REF:-HEAD}"
readonly FORCE_RECREATE="${FILTERED_PR_FORCE:-0}"
readonly PUSH_BRANCHES="${FILTERED_PR_PUSH:-1}"
readonly CREATE_PR="${FILTERED_PR_CREATE_PR:-1}"

TEMP_WORKTREE=""
CLEANUP_BASE_BRANCH=""
CLEANUP_HEAD_BRANCH=""
SUCCESS="false"
REMOTE_OWNER=""
REMOTE_REPO=""
PR_URL=""

ALLOWED_PATHS=(
    "src"
    "docker"
    "tests"
)

die() {
    echo "$*" >&2
    exit 1
}

usage() {
    cat <<'EOF'
Usage: ./tools/prepare-filtered-pr.sh

Creates two local branches for a PR whose diff is limited to the allowlisted
paths declared near the top of this script.

The synthetic base branch starts from the source commit and removes the
allowlisted paths entirely. The synthetic head branch then reapplies the
current allowlisted paths on top, so the PR reads as if the source branch only
introduced those directories.

Branch names:
  <name>-base
  <name>-head

Defaults:
  generated name current local timestamp (YYYY-MM-DD-HHMMSS)
  source ref   FILTERED_PR_SOURCE_REF=HEAD

Optional:
  FILTERED_PR_FORCE=1 recreates existing local <name>-base / <name>-head
  FILTERED_PR_PUSH=0 creates local branches only
  FILTERED_PR_CREATE_PR=0 pushes branches but skips PR creation

Result:
  By default, pushes both branches and opens the PR from <name>-head into
  <name>-base.
EOF
}

warn_if_worktree_dirty() {
    local status_output=""
    status_output="$(git status --short)"
    if [[ -n "${status_output}" ]]; then
        echo "warning: working tree is dirty; this tool uses ${SOURCE_REF} only and ignores uncommitted changes" >&2
    fi
}

validate_branch_name() {
    local branch_name="$1"
    git check-ref-format --branch "${branch_name}" >/dev/null 2>&1 || \
        die "invalid branch name: ${branch_name}"
}

branch_exists() {
    local branch_name="$1"
    git show-ref --verify --quiet "refs/heads/${branch_name}"
}

autogenerated_name() {
    date '+%Y-%m-%d-%H%M%S'
}

reset_branch_if_needed() {
    local branch_name="$1"

    if ! branch_exists "${branch_name}"; then
        return
    fi

    if [[ "${FORCE_RECREATE}" != "1" ]]; then
        die "branch already exists: ${branch_name} (set FILTERED_PR_FORCE=1 to recreate it)"
    fi

    git branch -D "${branch_name}" >/dev/null
}

verify_allowlisted_diff() {
    local base_branch="$1"
    local head_branch="$2"
    local diff_path=""

    while IFS= read -r diff_path; do
        [[ -z "${diff_path}" ]] && continue

        local allowed="false"
        local path_prefix=""
        for path_prefix in "${ALLOWED_PATHS[@]}"; do
            if [[ "${diff_path}" == "${path_prefix}/"* ]] || [[ "${diff_path}" == "${path_prefix}" ]]; then
                allowed="true"
                break
            fi
        done

        if [[ "${allowed}" != "true" ]]; then
            die "verification failed: ${base_branch}...${head_branch} still includes non-allowlisted path ${diff_path}"
        fi
    done < <(git diff --name-only "${base_branch}...${head_branch}")
}

load_remote_repo() {
    local origin_url=""
    origin_url="$(git remote get-url origin 2>/dev/null || true)"
    [[ -n "${origin_url}" ]] || die "origin remote is not configured"

    local repo_path=""
    if [[ "${origin_url}" =~ ^https://github\.com/(.+)$ ]]; then
        repo_path="${BASH_REMATCH[1]}"
    elif [[ "${origin_url}" =~ ^git@github\.com:(.+)$ ]]; then
        repo_path="${BASH_REMATCH[1]}"
    elif [[ "${origin_url}" =~ ^ssh://git@github\.com/(.+)$ ]]; then
        repo_path="${BASH_REMATCH[1]}"
    else
        die "origin remote is not a supported GitHub URL: ${origin_url}"
    fi

    repo_path="${repo_path%.git}"
    local extra_path=""
    IFS='/' read -r REMOTE_OWNER REMOTE_REPO extra_path <<< "${repo_path}"
    [[ -n "${REMOTE_OWNER}" ]] || die "failed to parse GitHub owner from origin remote"
    [[ -n "${REMOTE_REPO}" ]] || die "failed to parse GitHub repo from origin remote"
    [[ -z "${extra_path:-}" ]] || die "unexpected extra path segments in origin remote: ${origin_url}"
}

resolve_github_token() {
    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
        printf '%s\n' "${GITHUB_TOKEN}"
        return
    fi
    if [[ -n "${GH_TOKEN:-}" ]]; then
        printf '%s\n' "${GH_TOKEN}"
        return
    fi

    local credential_output=""
    credential_output="$(
        git credential fill <<'EOF'
protocol=https
host=github.com

EOF
    )" || die "failed to resolve GitHub credentials from git credential helper"

    local line=""
    local token=""
    while IFS= read -r line; do
        case "${line}" in
            password=*)
                token="${line#password=}"
                ;;
        esac
    done <<< "${credential_output}"

    [[ -n "${token}" ]] || die "no GitHub token found via GITHUB_TOKEN, GH_TOKEN, or git credential helper"
    printf '%s\n' "${token}"
}

push_branch() {
    local branch_name="$1"
    local push_args=()

    if [[ "${FORCE_RECREATE}" == "1" ]]; then
        push_args+=(--force-with-lease)
    fi

    git push "${push_args[@]}" origin "${branch_name}:${branch_name}" >/dev/null
}

json_string_field() {
    local json_path="$1"
    local json_file="$2"

    python3 - "${json_path}" "${json_file}" <<'PY'
import json
import sys

path = sys.argv[1]
json_file = sys.argv[2]
with open(json_file, "r", encoding="utf-8") as handle:
    data = json.load(handle)

value = data
for part in path.split("."):
    if isinstance(value, dict):
        value = value.get(part)
    else:
        value = None
        break

if isinstance(value, str):
    print(value)
PY
}

existing_pr_url() {
    local token="$1"
    local head_branch="$2"
    local base_branch="$3"
    local response_file="$4"

    curl -fsS --get \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${token}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        --data-urlencode "state=open" \
        --data-urlencode "head=${REMOTE_OWNER}:${head_branch}" \
        --data-urlencode "base=${base_branch}" \
        "https://api.github.com/repos/${REMOTE_OWNER}/${REMOTE_REPO}/pulls" \
        > "${response_file}"

    python3 - "${response_file}" <<'PY'
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as handle:
    pulls = json.load(handle)

if isinstance(pulls, list) and pulls:
    html_url = pulls[0].get("html_url")
    if isinstance(html_url, str):
        print(html_url)
PY
}

create_pr() {
    local name="$1"
    local base_branch="$2"
    local head_branch="$3"
    local token="$4"
    local title="${FILTERED_PR_TITLE:-Filtered code-only PR ${name}}"
    local body="${FILTERED_PR_BODY:-Automated filtered PR. Only allowlisted paths differ between ${base_branch} and ${head_branch}.}"

    local payload_file=""
    payload_file="$(mktemp "${TMPDIR:-/tmp}/prepare-filtered-pr-payload.XXXXXX")"
    local response_file=""
    response_file="$(mktemp "${TMPDIR:-/tmp}/prepare-filtered-pr-response.XXXXXX")"
    local lookup_file=""
    lookup_file="$(mktemp "${TMPDIR:-/tmp}/prepare-filtered-pr-existing.XXXXXX")"

    python3 - "${payload_file}" "${title}" "${body}" "${REMOTE_OWNER}:${head_branch}" "${base_branch}" <<'PY'
import json
import sys

payload_path = sys.argv[1]
title = sys.argv[2]
body = sys.argv[3]
head = sys.argv[4]
base = sys.argv[5]

with open(payload_path, "w", encoding="utf-8") as handle:
    json.dump(
        {
            "title": title,
            "head": head,
            "base": base,
            "body": body,
        },
        handle,
    )
PY

    local http_code=""
    http_code="$(
        curl -sS \
            -o "${response_file}" \
            -w '%{http_code}' \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${token}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -X POST \
            "https://api.github.com/repos/${REMOTE_OWNER}/${REMOTE_REPO}/pulls" \
            --data @"${payload_file}"
    )"

    if [[ "${http_code}" == "201" ]]; then
        PR_URL="$(json_string_field "html_url" "${response_file}")"
        rm -f -- "${payload_file}" "${response_file}" "${lookup_file}"
        [[ -n "${PR_URL}" ]] || die "PR was created but the GitHub response did not include html_url"
        return
    fi

    if [[ "${http_code}" == "422" ]]; then
        PR_URL="$(existing_pr_url "${token}" "${head_branch}" "${base_branch}" "${lookup_file}")"
        if [[ -n "${PR_URL}" ]]; then
            rm -f -- "${payload_file}" "${response_file}" "${lookup_file}"
            return
        fi
    fi

    local api_message=""
    api_message="$(json_string_field "message" "${response_file}")"
    rm -f -- "${payload_file}" "${response_file}" "${lookup_file}"
    [[ -n "${api_message}" ]] || api_message="unknown GitHub API error"
    die "failed to create PR via GitHub API (${http_code}): ${api_message}"
}

cleanup() {
    if [[ -n "${TEMP_WORKTREE}" ]]; then
        git worktree remove --force "${TEMP_WORKTREE}" >/dev/null 2>&1 || true
        rm -rf -- "${TEMP_WORKTREE}" >/dev/null 2>&1 || true
    fi

    if [[ "${SUCCESS}" == "true" ]]; then
        return
    fi

    if [[ -n "${CLEANUP_HEAD_BRANCH}" ]] && branch_exists "${CLEANUP_HEAD_BRANCH}"; then
        git branch -D "${CLEANUP_HEAD_BRANCH}" >/dev/null 2>&1 || true
    fi
    if [[ -n "${CLEANUP_BASE_BRANCH}" ]] && branch_exists "${CLEANUP_BASE_BRANCH}"; then
        git branch -D "${CLEANUP_BASE_BRANCH}" >/dev/null 2>&1 || true
    fi
}

trap cleanup EXIT

main() {
    if [[ "$#" -ne 0 ]]; then
        usage >&2
        exit 2
    fi

    cd -- "${REPO_ROOT}"

    git rev-parse --show-toplevel >/dev/null 2>&1 || die "not inside a git repository"
    warn_if_worktree_dirty

    if [[ "${CREATE_PR}" == "1" && "${PUSH_BRANCHES}" != "1" ]]; then
        die "FILTERED_PR_CREATE_PR=1 requires FILTERED_PR_PUSH=1"
    fi

    local name=""
    name="$(autogenerated_name)"
    local base_branch="${name}-base"
    local head_branch="${name}-head"
    CLEANUP_BASE_BRANCH="${base_branch}"
    CLEANUP_HEAD_BRANCH="${head_branch}"
    validate_branch_name "${base_branch}"
    validate_branch_name "${head_branch}"
    load_remote_repo

    git rev-parse --verify "${SOURCE_REF}^{commit}" >/dev/null 2>&1 || \
        die "source ref not found: ${SOURCE_REF}"

    local source_commit=""
    source_commit="$(git rev-parse "${SOURCE_REF}^{commit}")"

    reset_branch_if_needed "${base_branch}"
    reset_branch_if_needed "${head_branch}"

    TEMP_WORKTREE="$(mktemp -d "${TMPDIR:-/tmp}/prepare-filtered-pr.XXXXXX")"

    git worktree add --detach "${TEMP_WORKTREE}" "${source_commit}" >/dev/null

    (
        cd -- "${TEMP_WORKTREE}"

        git checkout -B "${base_branch}" "${source_commit}" >/dev/null
        git rm -r --ignore-unmatch -- "${ALLOWED_PATHS[@]}" >/dev/null
        if ! git diff --cached --quiet; then
            git -c core.hooksPath=/dev/null commit -m "Remove allowlisted paths for ${base_branch}" >/dev/null
        fi

        git checkout -B "${head_branch}" >/dev/null
        local allowed_path=""
        for allowed_path in "${ALLOWED_PATHS[@]}"; do
            git checkout "${source_commit}" -- "${allowed_path}" >/dev/null 2>&1 || true
        done
        if ! git diff --cached --quiet || ! git diff --quiet; then
            git -c core.hooksPath=/dev/null commit -m "Add allowlisted changes for ${name}" >/dev/null
        fi
    )

    verify_allowlisted_diff "${base_branch}" "${head_branch}"

    if [[ "${PUSH_BRANCHES}" == "1" ]]; then
        push_branch "${base_branch}"
        push_branch "${head_branch}"
    fi

    if [[ "${CREATE_PR}" == "1" ]]; then
        local github_token=""
        github_token="$(resolve_github_token)"
        create_pr "${name}" "${base_branch}" "${head_branch}" "${github_token}"
    fi

    SUCCESS="true"

    echo "Created filtered PR branches:"
    echo "  name: ${name}"
    echo "  base: ${base_branch}"
    echo "  head: ${head_branch}"
    echo "  source: ${SOURCE_REF} (${source_commit})"
    echo "  push: ${PUSH_BRANCHES}"
    echo "  create-pr: ${CREATE_PR}"
    echo
    if [[ -n "${PR_URL}" ]]; then
        echo "PR: ${PR_URL}"
    else
        echo "Open the PR from ${head_branch} into ${base_branch}."
    fi
    echo "Verify with: git diff --name-only ${base_branch}...${head_branch}"
}

main "$@"
